// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assets.sql

package sqlc

import (
	"context"
)

const getAssetByTicker = `-- name: GetAssetByTicker :one
SELECT id, ticker, name, asset_type, source, external_id, currency, market, created_at FROM assets WHERE LOWER(ticker) = LOWER($1) AND asset_type = $2
`

type GetAssetByTickerParams struct {
	Lower     string `json:"lower"`
	AssetType string `json:"asset_type"`
}

func (q *Queries) GetAssetByTicker(ctx context.Context, arg GetAssetByTickerParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByTicker, arg.Lower, arg.AssetType)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Name,
		&i.AssetType,
		&i.Source,
		&i.ExternalID,
		&i.Currency,
		&i.Market,
		&i.CreatedAt,
	)
	return i, err
}

const listAllAssets = `-- name: ListAllAssets :many
SELECT id, ticker, name, asset_type, source, external_id, currency, market, created_at FROM assets ORDER BY asset_type, ticker
`

func (q *Queries) ListAllAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAllAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.Name,
			&i.AssetType,
			&i.Source,
			&i.ExternalID,
			&i.Currency,
			&i.Market,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByType = `-- name: ListAssetsByType :many
SELECT id, ticker, name, asset_type, source, external_id, currency, market, created_at FROM assets WHERE asset_type = $1 ORDER BY ticker
`

func (q *Queries) ListAssetsByType(ctx context.Context, assetType string) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByType, assetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.Name,
			&i.AssetType,
			&i.Source,
			&i.ExternalID,
			&i.Currency,
			&i.Market,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAssets = `-- name: SearchAssets :many
SELECT id, ticker, name, asset_type, source, external_id, currency, market, created_at FROM assets
 WHERE (ticker ILIKE $1 OR name ILIKE $1)
   AND ($2 = '' OR asset_type = $2)
 ORDER BY (ticker ILIKE $1) DESC, ticker ASC
 LIMIT $3
`

type SearchAssetsParams struct {
	Ticker  string      `json:"ticker"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
}

// ILIKE on ticker OR name, optional asset_type filter, LIMIT $3.
// args: query string ("%val%"), asset_type or empty string, limit
func (q *Queries) SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, searchAssets, arg.Ticker, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.Name,
			&i.AssetType,
			&i.Source,
			&i.ExternalID,
			&i.Currency,
			&i.Market,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
