// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: investments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investments (portfolio_id, ticker, asset_type, amount_invested, quantity, purchase_date, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, portfolio_id, ticker, asset_type, amount_invested, quantity, purchase_date, notes, created_at, updated_at
`

type CreateInvestmentParams struct {
	PortfolioID    pgtype.UUID    `json:"portfolio_id"`
	Ticker         string         `json:"ticker"`
	AssetType      string         `json:"asset_type"`
	AmountInvested pgtype.Numeric `json:"amount_invested"`
	Quantity       pgtype.Numeric `json:"quantity"`
	PurchaseDate   pgtype.Date    `json:"purchase_date"`
	Notes          pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, createInvestment,
		arg.PortfolioID,
		arg.Ticker,
		arg.AssetType,
		arg.AmountInvested,
		arg.Quantity,
		arg.PurchaseDate,
		arg.Notes,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Ticker,
		&i.AssetType,
		&i.AmountInvested,
		&i.Quantity,
		&i.PurchaseDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvestment = `-- name: DeleteInvestment :exec
DELETE FROM investments
WHERE id = $1
`

func (q *Queries) DeleteInvestment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvestment, id)
	return err
}

const getInvestmentByID = `-- name: GetInvestmentByID :one
SELECT id, portfolio_id, ticker, asset_type, amount_invested, quantity, purchase_date, notes, created_at, updated_at
FROM investments
WHERE id = $1
`

func (q *Queries) GetInvestmentByID(ctx context.Context, id pgtype.UUID) (Investment, error) {
	row := q.db.QueryRow(ctx, getInvestmentByID, id)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Ticker,
		&i.AssetType,
		&i.AmountInvested,
		&i.Quantity,
		&i.PurchaseDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvestmentWithOwner = `-- name: GetInvestmentWithOwner :one
SELECT i.id, i.portfolio_id, i.ticker, i.asset_type, i.amount_invested, i.quantity, i.purchase_date, i.notes, i.created_at, i.updated_at, p.user_id
FROM investments i
JOIN portfolios p ON p.id = i.portfolio_id
WHERE i.id = $1
`

type GetInvestmentWithOwnerRow struct {
	ID             pgtype.UUID      `json:"id"`
	PortfolioID    pgtype.UUID      `json:"portfolio_id"`
	Ticker         string           `json:"ticker"`
	AssetType      string           `json:"asset_type"`
	AmountInvested pgtype.Numeric   `json:"amount_invested"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	PurchaseDate   pgtype.Date      `json:"purchase_date"`
	Notes          pgtype.Text      `json:"notes"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	UserID         pgtype.UUID      `json:"user_id"`
}

// joins through portfolios so handlers can check ownership in a single round trip.
func (q *Queries) GetInvestmentWithOwner(ctx context.Context, id pgtype.UUID) (GetInvestmentWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, getInvestmentWithOwner, id)
	var i GetInvestmentWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Ticker,
		&i.AssetType,
		&i.AmountInvested,
		&i.Quantity,
		&i.PurchaseDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listInvestmentsByPortfolio = `-- name: ListInvestmentsByPortfolio :many
SELECT id, portfolio_id, ticker, asset_type, amount_invested, quantity, purchase_date, notes, created_at, updated_at
FROM investments
WHERE portfolio_id = $1
ORDER BY purchase_date DESC, created_at DESC
`

func (q *Queries) ListInvestmentsByPortfolio(ctx context.Context, portfolioID pgtype.UUID) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByPortfolio, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Ticker,
			&i.AssetType,
			&i.AmountInvested,
			&i.Quantity,
			&i.PurchaseDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvestment = `-- name: UpdateInvestment :one
UPDATE investments
SET ticker = $2, asset_type = $3, amount_invested = $4, quantity = $5, purchase_date = $6, notes = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, portfolio_id, ticker, asset_type, amount_invested, quantity, purchase_date, notes, created_at, updated_at
`

type UpdateInvestmentParams struct {
	ID             pgtype.UUID    `json:"id"`
	Ticker         string         `json:"ticker"`
	AssetType      string         `json:"asset_type"`
	AmountInvested pgtype.Numeric `json:"amount_invested"`
	Quantity       pgtype.Numeric `json:"quantity"`
	PurchaseDate   pgtype.Date    `json:"purchase_date"`
	Notes          pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateInvestment(ctx context.Context, arg UpdateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, updateInvestment,
		arg.ID,
		arg.Ticker,
		arg.AssetType,
		arg.AmountInvested,
		arg.Quantity,
		arg.PurchaseDate,
		arg.Notes,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Ticker,
		&i.AssetType,
		&i.AmountInvested,
		&i.Quantity,
		&i.PurchaseDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
