// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Investment struct {
	ID             pgtype.UUID      `json:"id"`
	PortfolioID    pgtype.UUID      `json:"portfolio_id"`
	Ticker         string           `json:"ticker"`
	AssetType      string           `json:"asset_type"`
	AmountInvested pgtype.Numeric   `json:"amount_invested"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	PurchaseDate   pgtype.Date      `json:"purchase_date"`
	Notes          pgtype.Text      `json:"notes"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Portfolio struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	Name        string           `json:"name"`
	Type        string           `json:"type"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type PriceCache struct {
	ID        int32            `json:"id"`
	Ticker    string           `json:"ticker"`
	AssetType string           `json:"asset_type"`
	Price     pgtype.Numeric   `json:"price"`
	Currency  pgtype.Text      `json:"currency"`
	FetchedAt pgtype.Timestamp `json:"fetched_at"`
}

type PriceHistory struct {
	ID         int32          `json:"id"`
	Ticker     string         `json:"ticker"`
	AssetType  string         `json:"asset_type"`
	Price      pgtype.Numeric `json:"price"`
	Currency   pgtype.Text    `json:"currency"`
	RecordedAt pgtype.Date    `json:"recorded_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	Email             string           `json:"email"`
	PasswordHash      string           `json:"password_hash"`
	PreferredCurrency pgtype.Text      `json:"preferred_currency"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}
