// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: portfolio_snapshots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPortfolioSnapshotsInPeriod = `-- name: ListPortfolioSnapshotsInPeriod :many
SELECT id, portfolio_id, snapshot_date, total_value, currency, created_at
FROM portfolio_snapshots
WHERE portfolio_id = $1 AND snapshot_date >= $2
ORDER BY snapshot_date ASC
`

type ListPortfolioSnapshotsInPeriodParams struct {
	PortfolioID  pgtype.UUID `json:"portfolio_id"`
	SnapshotDate pgtype.Date `json:"snapshot_date"`
}

func (q *Queries) ListPortfolioSnapshotsInPeriod(ctx context.Context, arg ListPortfolioSnapshotsInPeriodParams) ([]PortfolioSnapshot, error) {
	rows, err := q.db.Query(ctx, listPortfolioSnapshotsInPeriod, arg.PortfolioID, arg.SnapshotDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortfolioSnapshot
	for rows.Next() {
		var i PortfolioSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.SnapshotDate,
			&i.TotalValue,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPortfolioSnapshot = `-- name: UpsertPortfolioSnapshot :exec
INSERT INTO portfolio_snapshots (portfolio_id, snapshot_date, total_value, currency)
VALUES ($1, $2, $3, $4)
ON CONFLICT (portfolio_id, snapshot_date) DO UPDATE
  SET total_value = EXCLUDED.total_value,
      currency = EXCLUDED.currency
`

type UpsertPortfolioSnapshotParams struct {
	PortfolioID  pgtype.UUID    `json:"portfolio_id"`
	SnapshotDate pgtype.Date    `json:"snapshot_date"`
	TotalValue   pgtype.Numeric `json:"total_value"`
	Currency     string         `json:"currency"`
}

func (q *Queries) UpsertPortfolioSnapshot(ctx context.Context, arg UpsertPortfolioSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertPortfolioSnapshot,
		arg.PortfolioID,
		arg.SnapshotDate,
		arg.TotalValue,
		arg.Currency,
	)
	return err
}
