// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: portfolios.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolios (user_id, name, type, description)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, type, description, created_at, updated_at
`

type CreatePortfolioParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, createPortfolio,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Description,
	)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePortfolio = `-- name: DeletePortfolio :exec
DELETE FROM portfolios
WHERE id = $1
`

func (q *Queries) DeletePortfolio(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePortfolio, id)
	return err
}

const getPortfolioByID = `-- name: GetPortfolioByID :one
SELECT id, user_id, name, type, description, created_at, updated_at
FROM portfolios
WHERE id = $1
`

func (q *Queries) GetPortfolioByID(ctx context.Context, id pgtype.UUID) (Portfolio, error) {
	row := q.db.QueryRow(ctx, getPortfolioByID, id)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPortfoliosByUser = `-- name: ListPortfoliosByUser :many
SELECT id, user_id, name, type, description, created_at, updated_at
FROM portfolios
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPortfoliosByUser(ctx context.Context, userID pgtype.UUID) ([]Portfolio, error) {
	rows, err := q.db.Query(ctx, listPortfoliosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Portfolio
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortfolio = `-- name: UpdatePortfolio :one
UPDATE portfolios
SET name = $2, type = $3, description = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, type, description, created_at, updated_at
`

type UpdatePortfolioParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRow(ctx, updatePortfolio,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Description,
	)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
