// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: prices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentPrice = `-- name: GetCurrentPrice :one
SELECT id, ticker, asset_type, price, currency, fetched_at FROM price_cache WHERE ticker = $1 AND asset_type = $2
`

type GetCurrentPriceParams struct {
	Ticker    string `json:"ticker"`
	AssetType string `json:"asset_type"`
}

func (q *Queries) GetCurrentPrice(ctx context.Context, arg GetCurrentPriceParams) (PriceCache, error) {
	row := q.db.QueryRow(ctx, getCurrentPrice, arg.Ticker, arg.AssetType)
	var i PriceCache
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.AssetType,
		&i.Price,
		&i.Currency,
		&i.FetchedAt,
	)
	return i, err
}

const snapshotPriceHistory = `-- name: SnapshotPriceHistory :exec
INSERT INTO price_history (ticker, asset_type, price, currency, recorded_at)
VALUES ($1, $2, $3, $4, CURRENT_DATE)
ON CONFLICT (ticker, asset_type, recorded_at) DO UPDATE
  SET price = EXCLUDED.price,
      currency = EXCLUDED.currency
`

type SnapshotPriceHistoryParams struct {
	Ticker    string         `json:"ticker"`
	AssetType string         `json:"asset_type"`
	Price     pgtype.Numeric `json:"price"`
	Currency  pgtype.Text    `json:"currency"`
}

func (q *Queries) SnapshotPriceHistory(ctx context.Context, arg SnapshotPriceHistoryParams) error {
	_, err := q.db.Exec(ctx, snapshotPriceHistory,
		arg.Ticker,
		arg.AssetType,
		arg.Price,
		arg.Currency,
	)
	return err
}

const upsertPrice = `-- name: UpsertPrice :one
INSERT INTO price_cache (ticker, asset_type, price, currency, fetched_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (ticker, asset_type) DO UPDATE
  SET price = EXCLUDED.price,
      currency = EXCLUDED.currency,
      fetched_at = EXCLUDED.fetched_at
RETURNING id, ticker, asset_type, price, currency, fetched_at
`

type UpsertPriceParams struct {
	Ticker    string         `json:"ticker"`
	AssetType string         `json:"asset_type"`
	Price     pgtype.Numeric `json:"price"`
	Currency  pgtype.Text    `json:"currency"`
}

func (q *Queries) UpsertPrice(ctx context.Context, arg UpsertPriceParams) (PriceCache, error) {
	row := q.db.QueryRow(ctx, upsertPrice,
		arg.Ticker,
		arg.AssetType,
		arg.Price,
		arg.Currency,
	)
	var i PriceCache
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.AssetType,
		&i.Price,
		&i.Currency,
		&i.FetchedAt,
	)
	return i, err
}
