// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error)
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteInvestment(ctx context.Context, id pgtype.UUID) error
	DeletePortfolio(ctx context.Context, id pgtype.UUID) error
	GetInvestmentByID(ctx context.Context, id pgtype.UUID) (Investment, error)
	// joins through portfolios so handlers can check ownership in a single round trip.
	GetInvestmentWithOwner(ctx context.Context, id pgtype.UUID) (GetInvestmentWithOwnerRow, error)
	GetPortfolioByID(ctx context.Context, id pgtype.UUID) (Portfolio, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListInvestmentsByPortfolio(ctx context.Context, portfolioID pgtype.UUID) ([]Investment, error)
	ListPortfoliosByUser(ctx context.Context, userID pgtype.UUID) ([]Portfolio, error)
	UpdateInvestment(ctx context.Context, arg UpdateInvestmentParams) (Investment, error)
	UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (Portfolio, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
