// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error)
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteInvestment(ctx context.Context, id pgtype.UUID) error
	DeletePortfolio(ctx context.Context, id pgtype.UUID) error
	GetAssetByTicker(ctx context.Context, arg GetAssetByTickerParams) (Asset, error)
	GetCurrentPrice(ctx context.Context, arg GetCurrentPriceParams) (PriceCache, error)
	GetInvestmentByID(ctx context.Context, id pgtype.UUID) (Investment, error)
	// joins through portfolios so handlers can check ownership in a single round trip.
	GetInvestmentWithOwner(ctx context.Context, id pgtype.UUID) (GetInvestmentWithOwnerRow, error)
	GetPortfolioByID(ctx context.Context, id pgtype.UUID) (Portfolio, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListAllAssets(ctx context.Context) ([]Asset, error)
	ListAllPortfolios(ctx context.Context) ([]Portfolio, error)
	ListAssetsByType(ctx context.Context, assetType string) ([]Asset, error)
	ListInvestmentsByPortfolio(ctx context.Context, portfolioID pgtype.UUID) ([]Investment, error)
	ListPortfolioSnapshotsInPeriod(ctx context.Context, arg ListPortfolioSnapshotsInPeriodParams) ([]PortfolioSnapshot, error)
	ListPortfoliosByUser(ctx context.Context, userID pgtype.UUID) ([]Portfolio, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	// ILIKE on ticker OR name, optional asset_type filter, LIMIT $3.
	// args: query string ("%val%"), asset_type or empty string, limit
	SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]Asset, error)
	SnapshotPriceHistory(ctx context.Context, arg SnapshotPriceHistoryParams) error
	UpdateInvestment(ctx context.Context, arg UpdateInvestmentParams) (Investment, error)
	UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (Portfolio, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpsertPortfolioSnapshot(ctx context.Context, arg UpsertPortfolioSnapshotParams) error
	UpsertPrice(ctx context.Context, arg UpsertPriceParams) (PriceCache, error)
}

var _ Querier = (*Queries)(nil)
